# Generated by Django 3.0.3 on 2020-03-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
